services:
  tg-contest-bot:
    container_name: ${NEW_CONTAINER_NAME}
#    image: ${NEW_IMAGE_NAME}:${VERSION}
    image: alpine:latest
    cpus: 0.4
    mem_limit: 256m
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - MAIN_DATABASE_DSN=/var/lib/tgcontestbot/main.db
    volumes:
      - ./bin/tgcontestbot:/usr/local/bin/tgcontestbot
      - ${VOLUME_NAME}:/var/lib/tgcontestbot:rw
    command: contestbot
    logging:
      driver: journald
      options:
        max-size: 10mb