services:
  tgbotcontest:
    env_file: .env
    restart: unless-stopped
    logging:
      driver: journald
    volumes:
      - ${DB_FILE}:/var/lib/tgbotcontest/main.db
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    container_name: tgbotcontest