services:
  tgbotcontest:
    env_file: .env
    restart: unless-stopped
    logging:
      driver: journald
    volumes:
      - ${DB_DIR}:/var/lib/tgbotcontest
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    container_name: tgbotcontest