name: deploy

on:
  push:
    branches:
      - main

env:
  DEPLOY_DIR: /home/${{ secrets.PROD_SSH_USERNAME }}/src/tgbotcontest

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH config
        run: |
          mkdir -p ~/.ssh
          cat <<EOF >> ~/.ssh/config
          Host Prod
            HostName ${{ secrets.PROD_SSH_HOST }}
            User ${{ secrets.PROD_SSH_USERNAME }}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          EOF
          chmod 600 ~/.ssh/config

      - name: Add SSH key
        run: |
          echo "${{ secrets.PROD_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Rsync copy project
        run: SSH_HOST=Prod DIR=${{ env.DEPLOY_DIR }}  ./scripts/rsync-project.sh

      - name: SSH Remote Commands
        run: |
          ssh Prod
          neofetch
