name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'окружение из settings/environments для деплоя'
        required: true
        type: string
      prefix:
        description: 'идентификатор экземпляра приложения. Например prod, dev, feature1'
        required: true
        type: string

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v7
        with:
          args: --timeout 10m

  deploy:
    runs-on: ubuntu-latest
    needs: golangci-lint
    environment: ${{ inputs.environment}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH config
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id
          chmod 600 ~/.ssh/id
          cat <<EOF >> ~/.ssh/config
          Host Prod
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USERNAME }}
            Port ${{ secrets.SSH_PORT }}
            IdentityFile ~/.ssh/id
            StrictHostKeyChecking no
          EOF
          chmod 600 ~/.ssh/config

      - name: Deploy
        run: |
          SSH_HOST=Prod \
          VERSION=${{ github.ref_name }} \
          APP_PREFIX=${{ inputs.prefix }} \
          TOKEN=${{ secrets.BOT_TOKEN }} \
          ./scripts/deploy.sh